import * as fs from 'fs';
import * as path from 'path';
import * as ort from 'onnxruntime-node';
import type { CustomerProfile } from '../models';

// ─────────────────────────────────────────────────────────────────────────────
// ML Inference Service
//
// Loads both ONNX models once at module initialisation and caches the sessions.
// The feature order is read from feature_order.json — Node never guesses the
// column order; it always reads from the file generated by the Python script.
//
// Why we read feature_order.json at runtime:
//   • The ONNX model weights bake in the column order used at training time.
//   • If the Python script is re-run with a different column order, Node will
//     automatically pick up the new order without a code change.
// ─────────────────────────────────────────────────────────────────────────────

const ML_DIR = path.join(__dirname, '..', 'ml');

// ── Feature order (loaded synchronously at module init) ───────────────────────

const featureOrderPath = path.join(ML_DIR, 'feature_order.json');

if (!fs.existsSync(featureOrderPath)) {
  throw new Error(
    `[MLInference] feature_order.json not found at ${featureOrderPath}. ` +
    'Run ml/train_models.py and copy the outputs to src/ml/.',
  );
}

const FEATURE_ORDER: string[] = JSON.parse(
  fs.readFileSync(featureOrderPath, 'utf-8'),
) as string[];

console.log(`[MLInference] Feature order loaded: [${FEATURE_ORDER.join(', ')}]`);

// ── ONNX session cache ────────────────────────────────────────────────────────

let purchaseSession: ort.InferenceSession | null = null;
let valueSession: ort.InferenceSession | null = null;

async function getPurchaseSession(): Promise<ort.InferenceSession> {
  if (!purchaseSession) {
    const modelPath = path.join(ML_DIR, 'purchase_model.onnx');
    if (!fs.existsSync(modelPath)) {
      throw new Error(
        `[MLInference] purchase_model.onnx not found at ${modelPath}. ` +
        'Run ml/train_models.py and copy the outputs to src/ml/.',
      );
    }
    purchaseSession = await ort.InferenceSession.create(modelPath);
    console.log('[MLInference] purchase_model.onnx session loaded ✓');
  }
  return purchaseSession;
}

async function getValueSession(): Promise<ort.InferenceSession> {
  if (!valueSession) {
    const modelPath = path.join(ML_DIR, 'value_model.onnx');
    if (!fs.existsSync(modelPath)) {
      throw new Error(
        `[MLInference] value_model.onnx not found at ${modelPath}. ` +
        'Run ml/train_models.py and copy the outputs to src/ml/.',
      );
    }
    valueSession = await ort.InferenceSession.create(modelPath);
    console.log('[MLInference] value_model.onnx session loaded ✓');
  }
  return valueSession;
}

// ── Pre-warm sessions on module load (non-blocking) ───────────────────────────
// We kick off session creation immediately so the first real request doesn't pay
// the cold-start cost. Errors here will be caught per-request in the functions below.
void Promise.all([getPurchaseSession(), getValueSession()]).catch((err: unknown) => {
  const msg = err instanceof Error ? err.message : String(err);
  console.warn(`[MLInference] Pre-warm failed — sessions will load on first request: ${msg}`);
});

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Build a feature vector from a CustomerProfile + current conversation signals.
 * The column order is driven ENTIRELY by `feature_order.json` — not hardcoded.
 *
 * @param profile    - CustomerProfile (or partial) from DigitalTwinAgent.
 * @param sentiment  - Sentiment score from BehaviorAgent [-1, 1].
 * @param urgency    - Urgency score from BehaviorAgent [0, 1].
 * @returns          Float32Array of features in the exact training order.
 */
export function buildFeatureVector(
  profile: Partial<CustomerProfile>,
  sentiment: number,
  urgency: number,
): number[] {
  // Map of field name → resolved value (with safe defaults)
  const featureMap: Record<string, number> = {
    budgetSensitivity: profile.budgetSensitivity ?? 0.5,
    buyingFrequency:   profile.buyingFrequency   ?? 0.5,
    responseSpeed:     profile.responseSpeed      ?? 0.5,
    lifetimeValue:     profile.lifetimeValue      ?? 0,
    sentiment,
    urgency,
  };

  // Build vector in the EXACT order from feature_order.json
  return FEATURE_ORDER.map((featureName) => {
    const value = featureMap[featureName];
    if (value === undefined) {
      throw new Error(
        `[MLInference] buildFeatureVector: unknown feature "${featureName}" in feature_order.json. ` +
        'Re-run ml/train_models.py to regenerate models with the current schema.',
      );
    }
    return value;
  });
}

/**
 * Run the purchase classifier and return a probability in [0, 1].
 *
 * The XGBClassifier is exported via predict_proba, so the ONNX model already
 * outputs probabilities — no sigmoid needed.
 *
 * @param features - Feature vector from buildFeatureVector().
 * @returns Purchase probability float in [0, 1].
 */
export async function predictPurchaseProbability(features: number[]): Promise<number> {
  try {
    const session = await getPurchaseSession();
    const inputName = session.inputNames[0];

    // Build a Float32 tensor with shape [1, n_features]
    const tensor = new ort.Tensor(
      'float32',
      Float32Array.from(features),
      [1, features.length],
    );

    const results = await session.run({ [inputName]: tensor });

    // XGBClassifier ONNX export: output name is 'probabilities' (a [1, 2] tensor)
    // index 0 = P(class 0), index 1 = P(class 1)
    const probOutput = results['probabilities'] ?? results[session.outputNames[1]] ?? results[session.outputNames[0]];

    if (!probOutput) {
      throw new Error('[MLInference] purchase model returned no probability output');
    }

    const data = probOutput.data as Float32Array;

    // If output is a [1, 2] probability array, take index 1 (P(purchase))
    // If it's a single scalar, take index 0
    const prob = data.length >= 2 ? data[1] : data[0];

    if (prob === undefined || isNaN(prob)) {
      throw new Error(`[MLInference] predictPurchaseProbability: invalid output value: ${String(prob)}`);
    }

    return Math.max(0, Math.min(1, prob)); // clamp to [0,1]
  } catch (err) {
    console.error('[MLInference] predictPurchaseProbability error:', (err as Error).message);
    throw err; // never silently return fake numbers
  }
}

/**
 * Run the order value regressor and return the expected order value (float).
 *
 * @param features - Feature vector from buildFeatureVector().
 * @returns Expected order value as a positive float.
 */
export async function predictExpectedOrderValue(features: number[]): Promise<number> {
  try {
    const session = await getValueSession();
    const inputName = session.inputNames[0];

    const tensor = new ort.Tensor(
      'float32',
      Float32Array.from(features),
      [1, features.length],
    );

    const results = await session.run({ [inputName]: tensor });

    // XGBRegressor ONNX export: single output named 'variable' or first output
    const output = results['variable'] ?? results[session.outputNames[0]];

    if (!output) {
      throw new Error('[MLInference] value model returned no output');
    }

    const data = output.data as Float32Array;
    const value = data[0];

    if (value === undefined || isNaN(value)) {
      throw new Error(`[MLInference] predictExpectedOrderValue: invalid output value: ${String(value)}`);
    }

    return Math.max(0, value); // order values can't be negative
  } catch (err) {
    console.error('[MLInference] predictExpectedOrderValue error:', (err as Error).message);
    throw err; // never silently return fake numbers
  }
}

const mlInferenceService = {
  buildFeatureVector,
  predictPurchaseProbability,
  predictExpectedOrderValue,
  FEATURE_ORDER,
};

export default mlInferenceService;
