import type { CustomerProfile } from '../models';
import type { RedisMessage } from '../services/redis.service';

// ─────────────────────────────────────────────────────────────────────────────
// AgentState — the shared context object that flows through every agent in the
// pipeline.  Each agent reads from it and writes its enriched data back into it.
// ─────────────────────────────────────────────────────────────────────────────

export interface AgentState {
  /** UUID of the end-user (maps to User.id in Prisma) */
  userId: string;

  /** UUID of the business this conversation belongs to */
  businessId: string;

  /** The latest inbound message from the user */
  message: string;

  /** Conversation history loaded from Redis */
  history: RedisMessage[];

  /** Customer behavioural profile loaded from Postgres (null before DigitalTwin runs) */
  profile: Partial<CustomerProfile> | null;

  /** Intent label extracted by the BehaviorAgent (e.g. "purchase_intent") */
  intent: string | null;

  /** Sentiment score in [-1.0, 1.0], set by BehaviorAgent */
  sentiment: number | null;

  /** Urgency score in [0.0, 1.0], set by BehaviorAgent */
  urgency: number | null;

  /** Final natural-language reply generated by the ExecutionAgent */
  response: string | null;

  // ── Phase 2 fields ─────────────────────────────────────────────────────────

  /** ML-derived predictions from RevenuePredictionAgent (optional until that agent runs) */
  predictions?: {
    purchaseProbability: number;
    expectedOrderValue: number;
    ltv: number;
  };

  /** Customer segment label assigned by SegmentationAgent */
  segment?: 'high-value' | 'new' | 'frequent-buyer' | 'price-sensitive' | 'at-risk';

  /** Recommended strategy from StrategyDecisionAgent */
  strategy?: {
    discount: number;
    bundle: string[];
    reason: string;
    followUpTime: string | null;
    /** The DB Strategy row ID — needed by FeedbackAgent */
    strategyId?: string;
  };

  /** Optimised offer from OfferOptimizationAgent (ephemeral — not written to DB) */
  offer?: {
    headline: string;
    discountPercent: number;
    bundleItems: string[];
    copyHint: string;
  };

  // ── Phase 3 fields ─────────────────────────────────────────────────────────

  /** Competitor pricing / seasonal data from CompetitorIntelligenceAgent */
  competitor_factors?: {
    avgCompetitorPrice: number;
    maxSeasonalFactor: number;
  };

  /** The channel this message arrived on ("whatsapp" | "api") */
  channel?: 'whatsapp' | 'api';
}
