import type { CustomerProfile } from '../models';
import type { RedisMessage } from '../services/redis.service';

// ─────────────────────────────────────────────────────────────────────────────
// AgentState — the shared context object that flows through every agent in the
// pipeline.  Each agent reads from it and writes its enriched data back into it.
// ─────────────────────────────────────────────────────────────────────────────

export interface AgentState {
  /** UUID of the end-user (maps to User.id in Prisma) */
  userId: string;

  /** UUID of the business this conversation belongs to */
  businessId: string;

  /** The latest inbound message from the user */
  message: string;

  /** Conversation history loaded from Redis */
  history: RedisMessage[];

  /** Customer behavioural profile loaded from Postgres (null before DigitalTwin runs) */
  profile: Partial<CustomerProfile> | null;

  /** Intent label extracted by the BehaviorAgent (e.g. "purchase_intent") */
  intent: string | null;

  /** Sentiment score in [-1.0, 1.0], set by BehaviorAgent */
  sentiment: number | null;

  /** Urgency score in [0.0, 1.0], set by BehaviorAgent */
  urgency: number | null;

  /** Final natural-language reply generated by the ExecutionAgent */
  response: string | null;
}
